const data={
"schema-json-ld-generator":{t:"Schema JSON-LD Generator",h:"Generate clean Schema markup for your product page.",d:"Create Product, FAQ, and SoftwareApplication JSON-LD drafts.",f:["Product name","Website URL","Short description","FAQ questions"],o:v=>`<script type="application/ld+json">\\n${JSON.stringify({"@context":"https://schema.org","@type":"SoftwareApplication",name:v[0],url:v[1],description:v[2],applicationCategory:"BusinessApplication"},null,2)}\\n</script>`},
"comparison-page-generator":{t:"Comparison Page Generator",h:"Draft a competitor comparison page outline.",d:"Turn your positioning into a useful alternative page.",f:["Your product","Competitor","Main advantage","Target user"],o:v=>`# ${v[0]} vs ${v[1]}\\n\\nBest for: ${v[3]}\\n\\nWhy choose ${v[0]}:\\n- ${v[2]}\\n- Clear pricing and simple onboarding\\n- Better fit for focused teams\\n\\nInclude sections: features, pricing, use cases, migration, FAQ.`},
"ai-answer-prompt-tester":{t:"AI Answer Prompt Tester",h:"Create prompts to test how AI describes your product.",d:"Use these prompts in ChatGPT, Perplexity, Gemini, or Claude.",f:["Product name","Category","Target buyer","Key use case"],o:v=>`Test prompts:\\n1. What is ${v[0]}?\\n2. Best ${v[1]} tools for ${v[2]}?\\n3. When should someone use ${v[0]} for ${v[3]}?\\n4. Compare ${v[0]} with top alternatives.\\n5. Cite pages that explain ${v[0]}.`},
"brand-mention-tracker-sheet":{t:"Brand Mention Tracker Sheet",h:"Create a simple brand mention tracking table.",d:"Track AI answers, Reddit mentions, reviews, and citations.",f:["Brand name","Main keyword","Competitors","Review cadence"],o:v=>`Columns:\\nDate | Source | Query | Mentioned ${v[0]}? | Competitors: ${v[2]} | Sentiment | URL | Next action\\n\\nWeekly query: ${v[1]}\\nCadence: ${v[3]}`},
"product-positioning-extractor":{t:"Product Positioning Extractor",h:"Turn messy notes into clear positioning.",d:"Extract audience, problem, promise, and proof.",f:["Product","Audience","Pain point","Proof"],o:v=>`${v[0]} helps ${v[1]} solve ${v[2]} by giving them a faster, clearer workflow.\\n\\nPositioning:\\n- Audience: ${v[1]}\\n- Pain: ${v[2]}\\n- Promise: faster decision and execution\\n- Proof: ${v[3]}`},
"source-citation-checklist":{t:"Source Citation Checklist",h:"Check if your pages are easy for AI search to cite.",d:"Score citation readiness for AI visibility.",f:["Product page URL","Docs or FAQ URL","Comparison page URL","Proof page URL"],o:v=>`Citation checklist:\\n- Product page: ${v[0]}\\n- FAQ/docs: ${v[1]}\\n- Comparison page: ${v[2]}\\n- Proof/reviews: ${v[3]}\\n\\nAdd clear headings, short answers, dates, author/company info, and examples.`},
"reddit-signal-planner":{t:"Reddit Signal Planner",h:"Plan helpful Reddit participation without spam.",d:"Find safe contribution angles before sharing any link.",f:["Target subreddit","Common problem","Helpful answer angle","Tool link"],o:v=>`Subreddit: ${v[0]}\\nProblem to answer: ${v[1]}\\nHelpful angle: ${v[2]}\\n\\nRules:\\n1. Answer first, link only if asked or clearly useful.\\n2. Mention affiliation.\\n3. Track questions for future tool ideas.\\nOptional link: ${v[3]}`},
"product-hunt-launch-page-checker":{t:"Product Hunt Launch Page Checker",h:"Check if your launch page is ready.",d:"Prepare tagline, problem, demo, makers comment, and first comments.",f:["Product","Tagline","Primary user","Demo URL"],o:v=>`Launch checklist for ${v[0]}:\\n- Tagline: ${v[1]}\\n- User: ${v[2]}\\n- Demo: ${v[3]}\\n- Add screenshots\\n- Maker comment: problem, why built, what is free, what is paid\\n- Ask 5 friendly users for feedback, not votes.`},
"ai-search-snippet-optimizer":{t:"AI Search Snippet Optimizer",h:"Write snippets AI search can understand.",d:"Create short descriptions for homepage, FAQ, and social bios.",f:["Product","Audience","Main outcome","Keyword"],o:v=>`Homepage snippet:\\n${v[0]} helps ${v[1]} ${v[2]}.\\n\\nFAQ answer:\\n${v[0]} is a ${v[3]} tool for ${v[1]} who need ${v[2]}.\\n\\nBio:\\nFree ${v[3]} tools for ${v[1]}.`},
"review-page-brief-generator":{t:"Review Page Brief Generator",h:"Plan a page that collects proof and testimonials.",d:"Create sections for reviews, quotes, use cases, and outcomes.",f:["Product","Best user type","Main benefit","Proof source"],o:v=>`Review page brief for ${v[0]}:\\n- Hero: trusted by ${v[1]}\\n- Main benefit: ${v[2]}\\n- Proof source: ${v[3]}\\n- Add 3 short quotes, 2 before/after examples, FAQ, and CTA.`},
"use-case-page-generator":{t:"Use Case Page Generator",h:"Draft a use-case page outline for AI search.",d:"Create specific pages AI can cite for buyer intent queries.",f:["Product","Use case","User role","Outcome"],o:v=>`# ${v[0]} for ${v[1]}\\n\\nWho it is for: ${v[2]}\\nOutcome: ${v[3]}\\n\\nSections:\\n1. Problem\\n2. Workflow\\n3. Example\\n4. Common mistakes\\n5. FAQ\\n6. CTA`},
"competitor-mention-map":{t:"Competitor Mention Map",h:"Map how your product should appear beside alternatives.",d:"Create positioning notes for competitor and alternative pages.",f:["Your product","Competitors","Your edge","Weakness to avoid"],o:v=>`Mention map:\\nYour product: ${v[0]}\\nCompetitors: ${v[1]}\\nEdge: ${v[2]}\\nAvoid claiming: ${v[3]}\\n\\nCreate pages for: alternatives, comparison, migration, pricing, FAQ.`}
};
const id=document.body.dataset.tool, x=data[id], form=document.querySelector("#form"), out=document.querySelector("#out");
document.title=x.t; document.querySelector("#title").textContent=x.h; document.querySelector("#desc").textContent=x.d; document.querySelector("#cardTitle").textContent=x.t;
form.innerHTML=x.f.map((n,i)=>`<label>${n}<textarea id="f${i}" rows="2" placeholder="${n}"></textarea></label>`).join("")+`<button class="button primary full" id="go" type="button">Generate</button>`;
go.onclick=()=>{out.innerHTML="<pre></pre>";out.querySelector("pre").textContent=x.o(x.f.map((_,i)=>document.querySelector("#f"+i).value||x.f[i]));};
