const data={
"gumroad-product-page-checklist":{t:"Gumroad Product Page Checklist",h:"Check your Gumroad page before publishing.",d:"Catch missing proof, unclear benefits, weak pricing, and bad file delivery.",f:["Product name","Target buyer","Main outcome"],o:v=>`Checklist for ${v[0]}:\n- Buyer is clear: ${v[1]}\n- Outcome is visible above the fold: ${v[2]}\n- Includes 5-7 bullets of what buyers get\n- Has a refund/support note\n- Has screenshots or preview images\n- Price matches the depth of the kit\n- Gumroad file is uploaded and tested\n- Main free tool links back to this product`},
"gumroad-description-generator":{t:"Gumroad Description Generator",h:"Write a clear Gumroad sales description.",d:"Create a short product page description for digital downloads.",f:["Product","Buyer","Included items","Price"],o:v=>`${v[0]} helps ${v[1]} get organized faster without starting from scratch.\n\nUse it when you need a practical, reusable kit instead of another blank document.\n\nIncludes:\n${v[2]}\n\nBest for: ${v[1]}\nPrice: ${v[3]}\nInstant download after purchase.`},
"digital-product-idea-validator":{t:"Digital Product Idea Validator",h:"Score a small digital product idea.",d:"Check pain, buyer, speed to build, and monetization before creating it.",f:["Idea","Buyer","Pain","Paid upgrade"],o:v=>`Idea: ${v[0]}\nBuyer: ${v[1]}\nPain: ${v[2]}\nPaid upgrade: ${v[3]}\n\nValidation score:\n- Pain repeats weekly: yes/no\n- Buyer can be reached in communities: yes/no\n- Free tool can be built in one day: yes/no\n- Paid kit can be delivered as files: yes/no\n\nNext step: publish a free tool first, then add the paid kit link.`},
"product-pricing-calculator":{t:"Product Pricing Calculator",h:"Pick a simple price for a digital product.",d:"Estimate a starter price based on usefulness and depth.",f:["Product type","Time saved","Buyer type","Number of templates/files"],o:v=>`Pricing suggestion:\nProduct: ${v[0]}\nTime saved: ${v[1]}\nBuyer: ${v[2]}\nFiles/templates: ${v[3]}\n\nStarter price: $9-$19\nIf it saves money or helps earn money: $19-$39\nIf it is just a checklist: $5-$12\nUse lifetime pricing first; add subscriptions later only for updates.`},
"lead-magnet-idea-generator":{t:"Lead Magnet Idea Generator",h:"Create a free lead magnet idea.",d:"Turn a buyer pain into a simple free download or tool.",f:["Audience","Pain","Paid product"],o:v=>`Lead magnet ideas for ${v[0]}:\n1. Checklist: How to avoid ${v[1]}\n2. Template: Start solving ${v[1]} today\n3. Mini calculator: Estimate the cost of ${v[1]}\n4. Swipe file: Examples before buying ${v[2]}\n\nCTA: Get the full ${v[2]} kit for reusable templates.`},
"newsletter-subject-line-tester":{t:"Newsletter Subject Line Tester",h:"Improve a newsletter subject line.",d:"Generate clearer subject line variants for creators.",f:["Topic","Audience","Benefit"],o:v=>`Subject line options:\n- ${v[0]}: a practical guide for ${v[1]}\n- How ${v[1]} can ${v[2]}\n- The simple way to start ${v[0]}\n- Avoid this mistake when working on ${v[0]}\n- ${v[2]} without overcomplicating it\n\nPick the clearest promise, not the cleverest line.`},
"youtube-title-generator":{t:"YouTube Title Generator",h:"Generate searchable YouTube titles.",d:"Create title ideas with clear topic, audience, and result.",f:["Topic","Audience","Result"],o:v=>`YouTube title ideas:\n1. ${v[0]} for ${v[1]}: ${v[2]}\n2. I tried ${v[0]} so ${v[1]} do not have to\n3. How to ${v[2]} with ${v[0]}\n4. ${v[0]} mistakes ${v[1]} should avoid\n5. The simple ${v[0]} workflow for ${v[1]}`},
"tiktok-hook-generator":{t:"TikTok Hook Generator",h:"Write short-form video hooks.",d:"Create first-line hooks for TikTok, Reels, and Shorts.",f:["Audience","Problem","Outcome"],o:v=>`Hook ideas:\n- If you are ${v[0]}, stop doing this.\n- This is why ${v[1]} keeps happening.\n- I fixed ${v[1]} with one simple workflow.\n- ${v[0]} can get ${v[2]} without overthinking it.\n- Save this before you work on ${v[1]}.`},
"x-thread-outline-generator":{t:"X Thread Outline Generator",h:"Draft a clear X thread outline.",d:"Turn an idea into a useful build-in-public thread.",f:["Topic","Audience","Lesson"],o:v=>`Thread outline:\n1. Hook: Most ${v[1]} struggle with ${v[0]}.\n2. Context: What I noticed.\n3. Mistake: What people usually do.\n4. Lesson: ${v[2]}\n5. Example: Show the workflow.\n6. CTA: Ask what they want next.`},
"reddit-comment-draft-helper":{t:"Reddit Comment Draft Helper",h:"Draft helpful Reddit replies without spam.",d:"Create community-first comments that avoid hard selling.",f:["Post problem","Your useful advice","Relevant tool"],o:v=>`Comment draft:\n\nI would start by separating the problem into two parts: ${v[0]} and the repeatable workflow around it.\n\nWhat has helped me is: ${v[1]}.\n\nIf useful, I also made a small free tool for this kind of workflow: ${v[2]}. No pressure; the main thing is to fix the process first.`},
"case-study-generator":{t:"Case Study Generator",h:"Turn a result into a simple case study.",d:"Create proof copy for agencies, freelancers, and creators.",f:["Client/audience","Problem","Action","Result"],o:v=>`Case study draft:\n\nClient: ${v[0]}\nProblem: ${v[1]}\nAction: ${v[2]}\nResult: ${v[3]}\n\nBefore: The workflow was unclear and hard to repeat.\nAfter: The process became easier to follow, measure, and improve.\n\nUse this as website proof or a Gumroad preview.`},
"testimonial-request-email-generator":{t:"Testimonial Request Email Generator",h:"Ask for testimonials politely.",d:"Generate a short request after delivering value.",f:["Customer name","Product/service","Specific outcome"],o:v=>`Hi ${v[0]},\n\nThanks again for using ${v[1]}. If it helped with ${v[2]}, would you be open to sharing a short testimonial?\n\nA simple 1-2 sentence note is perfect. You could mention what problem you had, what changed, and who you would recommend it to.\n\nThank you!`},
"mini-course-outline-generator":{t:"Mini Course Outline Generator",h:"Plan a small paid or free course.",d:"Create a focused mini-course outline from one outcome.",f:["Course topic","Audience","Outcome"],o:v=>`Mini course: ${v[0]}\nAudience: ${v[1]}\nOutcome: ${v[2]}\n\nLesson 1: The problem and why it matters\nLesson 2: The simple framework\nLesson 3: Walkthrough example\nLesson 4: Common mistakes\nLesson 5: Checklist and next steps\n\nBonus: template or worksheet.`},
"digital-download-checklist":{t:"Digital Download Checklist",h:"Check a digital download before launch.",d:"Make sure files, previews, price, and support are ready.",f:["Product","Files included","Support email"],o:v=>`Launch checklist for ${v[0]}:\n- ZIP file opens correctly\n- Includes: ${v[1]}\n- README or start-here file included\n- Gumroad description explains the outcome\n- Preview image uploaded\n- Price and URL checked\n- Support email: ${v[2]}\n- Test purchase/download if possible`},
"canva-asset-brief-generator":{t:"Canva Asset Brief Generator",h:"Write a Canva design brief.",d:"Create a brief for covers, social images, and Gumroad previews.",f:["Product","Audience","Style","Required sizes"],o:v=>`Canva brief:\nProduct: ${v[0]}\nAudience: ${v[1]}\nStyle: ${v[2]}\nSizes: ${v[3]}\n\nInclude:\n- Product title\n- One outcome-focused subtitle\n- 3 benefit bullets\n- Clean screenshot/mockup area\n- Strong contrast and readable text\n- Export as PNG for product preview`}
};
const id=document.body.dataset.tool,x=data[id],form=document.querySelector("#form"),out=document.querySelector("#out");
document.title=x.t; title.textContent=x.h; desc.textContent=x.d; cardTitle.textContent=x.t;
form.innerHTML=x.f.map((n,i)=>`<label>${n}<textarea id="f${i}" rows="2" placeholder="${n}"></textarea></label>`).join("")+`<button class="button primary full" id="go" type="button">Generate</button>`;
go.onclick=()=>{out.innerHTML="<pre></pre>";out.querySelector("pre").textContent=x.o(x.f.map((_,i)=>document.querySelector("#f"+i).value||x.f[i]));};
