const data={
"pdf-page-reorder-planner":{t:"PDF Page Reorder Planner",h:"Plan the cleanest order before merging a PDF.",d:"Create a recruiter, client, or school-friendly document sequence.",f:["Pack purpose","Files included","Most important document"],o:v=>`Recommended order for ${v[0]}:\\n1. ${v[2]}\\n2. Cover or intro page\\n3. Supporting files: ${v[1]}\\n4. References or appendix\\n\\nTip: put the decision-making document first.`},
"image-to-pdf-converter":{t:"Image to PDF Converter",h:"Prepare images for a clean PDF bundle.",d:"Plan image order, names, and print settings before converting.",f:["PDF name","Image list","Page size"],o:v=>`Image PDF plan: ${v[0]}\\nPage size: ${v[2]}\\nOrder:\\n${v[1]}\\n\\nUse browser Print > Save as PDF after placing images in order.`},
"pdf-to-images-extractor":{t:"PDF to Images Extractor",h:"Plan preview images from a PDF.",d:"Choose pages to turn into product screenshots or thumbnails.",f:["PDF purpose","Pages to export","Image naming prefix"],o:v=>`Export plan:\\nPurpose: ${v[0]}\\nPages: ${v[1]}\\nNames: ${v[2]}-page-01.png, ${v[2]}-page-02.png\\nUse these for Gumroad previews or documentation.`},
"pdf-cover-page-maker":{t:"PDF Cover Page Maker",h:"Write a polished cover page for any PDF.",d:"Generate title, subtitle, recipient, and contents text.",f:["Title","Subtitle","Recipient","Included sections"],o:v=>`${v[0]}\\n${v[1]}\\nPrepared for: ${v[2]}\\n\\nIncludes:\\n${v[3]}\\n\\nPrepared on: ${new Date().toLocaleDateString()}`},
"pdf-filename-cleaner":{t:"PDF Filename Cleaner",h:"Create clear PDF file names.",d:"Avoid messy names like final_v3_real_final.pdf.",f:["Your name or brand","Document type","Client/company","Date"],o:v=>`${v[0]}-${v[2]}-${v[1]}-${v[3]}.pdf\\n${v[2]}-${v[1]}-${v[0]}.pdf\\n${v[1]}-${v[0]}-${v[3]}.pdf`},
"pdf-checklist-before-sending":{t:"PDF Checklist Before Sending",h:"Check a PDF before you send it.",d:"Avoid wrong files, missing pages, and private metadata.",f:["Recipient","Document purpose","Files included"],o:v=>`Before sending to ${v[0]}:\\n- File opens correctly\\n- Purpose is clear: ${v[1]}\\n- Included files: ${v[2]}\\n- Pages are in order\\n- File name is professional\\n- No private notes or comments\\n- Email has a short context line`},
"contract-pdf-summary-checklist":{t:"Contract PDF Summary Checklist",h:"Summarize a contract before signing.",d:"Create a plain-English review checklist for freelancers.",f:["Contract type","Client/vendor","Key concern"],o:v=>`Contract review: ${v[0]} with ${v[1]}\\nCheck:\\n- Scope of work\\n- Payment amount and timing\\n- Revision limits\\n- Ownership/IP\\n- Cancellation terms\\n- Liability\\n- Key concern: ${v[2]}\\n\\nNot legal advice; use this as a reading checklist.`},
"invoice-pdf-generator":{t:"Invoice PDF Generator",h:"Draft a simple invoice you can save as PDF.",d:"Create invoice text for freelancers and consultants.",f:["Seller","Client","Service","Amount"],o:v=>`INVOICE\\nFrom: ${v[0]}\\nBill to: ${v[1]}\\nService: ${v[2]}\\nAmount due: ${v[3]}\\nDue date: Net 15\\n\\nThank you for your business.`},
"receipt-pdf-generator":{t:"Receipt PDF Generator",h:"Draft a clean receipt.",d:"Create receipt text for simple sales or services.",f:["Seller","Buyer","Item/service","Paid amount"],o:v=>`RECEIPT\\nSeller: ${v[0]}\\nBuyer: ${v[1]}\\nItem/service: ${v[2]}\\nPaid: ${v[3]}\\nDate: ${new Date().toLocaleDateString()}\\nStatus: Paid`},
"certificate-pdf-maker":{t:"Certificate PDF Maker",h:"Create certificate wording.",d:"Draft a completion certificate for courses and workshops.",f:["Recipient","Course/event","Issuer","Date"],o:v=>`CERTIFICATE OF COMPLETION\\n\\nThis certifies that ${v[0]} completed ${v[1]}.\\n\\nIssued by: ${v[2]}\\nDate: ${v[3]}\\n\\nSignature: __________________`},
"one-page-proposal-pdf-maker":{t:"One-Page Proposal PDF Maker",h:"Draft a simple one-page proposal.",d:"Create proposal copy for consultants and freelancers.",f:["Client","Problem","Solution","Price"],o:v=>`Proposal for ${v[0]}\\n\\nProblem:\\n${v[1]}\\n\\nSolution:\\n${v[2]}\\n\\nDeliverables:\\n- Discovery\\n- Implementation\\n- Review\\n\\nPrice: ${v[3]}\\nNext step: approve and schedule kickoff.`},
"pdf-metadata-checklist":{t:"PDF Metadata Checklist",h:"Check PDF privacy before sharing.",d:"Avoid exposing author names, comments, or hidden data.",f:["File purpose","Audience","Sensitive items"],o:v=>`Metadata checklist for ${v[0]}:\\nAudience: ${v[1]}\\nRemove/check:\\n- Author metadata\\n- Comments and annotations\\n- Hidden pages\\n- Old file names\\n- Sensitive items: ${v[2]}\\n- Open the final PDF in a fresh viewer before sending.`},
"client-onboarding-pdf-pack-builder":{t:"Client Onboarding PDF Pack Builder",h:"Plan a client onboarding PDF pack.",d:"Create a structured welcome pack for freelancers.",f:["Client type","Services","Next steps"],o:v=>`Client onboarding pack for ${v[0]}:\\n1. Welcome note\\n2. Services included: ${v[1]}\\n3. Timeline\\n4. Communication rules\\n5. Files needed from client\\n6. Next steps: ${v[2]}\\n7. FAQ and support contact`}
};
const id=document.body.dataset.tool,x=data[id],form=document.querySelector("#form"),out=document.querySelector("#out");
document.title=x.t; title.textContent=x.h; desc.textContent=x.d; cardTitle.textContent=x.t;
form.innerHTML=x.f.map((n,i)=>`<label>${n}<textarea id="f${i}" rows="2" placeholder="${n}"></textarea></label>`).join("")+`<button class="button primary full" id="go" type="button">Generate</button>`;
go.onclick=()=>{out.innerHTML="<pre></pre>";out.querySelector("pre").textContent=x.o(x.f.map((_,i)=>document.querySelector("#f"+i).value||x.f[i]));};
